# --- CORE ---
WEBHOOK_PASSPHRASE=1234
OANDA_ENV=practice

# --- PAIRS ---
PAIRS=EUR_USD,GBP_USD,USD_JPY

# --- POSITION SIZE (SAFE MODE) ---
FIXED_UNITS=10000
FALLBACK_UNITS=10000
MAX_UNITS=10000
RISK_PERCENT=0

# --- TRADE CONTROL ---
MAX_OPEN_TRADES=1
MAX_TOTAL_OPEN_TRADES=2
MAX_TRADES_PER_PAIR=1
MIN_SECONDS_BETWEEN_TRADES=900

# --- RISK MANAGEMENT ---
STOP_LOSS_PIPS=10
TAKE_PROFIT_PIPS=12
MAX_DAILY_LOSS_PERCENT=3

# --- SPREAD / ENTRY FILTERS ---
MAX_SPREAD_PIPS=2.5
MIN_CANDLE_RANGE_PIPS=2
TREND_STRENGTH_MIN=15

# --- BREAK EVEN ---
USE_BREAK_EVEN=true
BREAK_EVEN_TRIGGER_PIPS=4
BREAK_EVEN_PLUS_PIPS=1

# --- TRAILING STOP ---
USE_TRAILING_STOP=true
TRAILING_TRIGGER_PIPS=6
TRAILING_DISTANCE_PIPS=3

# --- EXECUTION ---
MANAGE_INTERVAL_SECONDS=10
